WIP
katzenpost/ctidh_cgo pull request #5
Opened 2023-04-23 01:28 UTC by david415

2023-05-20 16:01 UTC, threebithacker requested changes

2023-05-22 04:10 UTC, david415 commented on common.go
> +		(*(*uint32)(unsafe.Pointer(p))) = uint32(buf[i])
Thank you for this review. I'll try to fix this tomorrow.

2023-05-23 06:49 UTC, david415 commented on common.go
> +		(*(*uint32)(unsafe.Pointer(p))) = uint32(buf[i])
@threebithacker it's 32-bit aligned because i found that 4 bytes was the smallest amount of entropy requested by the CTIDH library... and i figured it would be more efficient to copy 4 bytes at a time rather than just one byte.

2023-05-23 08:27 UTC, david415 commented on common.go
> +		(*(*uint32)(unsafe.Pointer(p))) = uint32(buf[i])
Fixed!

2023-10-27 03:06 UTC, merged